title: Homey Inspire
author: "@jekyllrb"
email: your-email@domain.com
description: > # this means to ignore newlines until "twitter_username:"
  Keren dengan casing beken.
tagline: Your home inspiration
permalink: /:year/:month/:day/:title.html
url: ""
baseurl: ""

plugins:
  - jekyll-sitemap
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num/"
